/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helloService_H
#define helloService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "hello_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class helloServiceIf {
 public:
  virtual ~helloServiceIf() {}
  virtual void hello_func(std::string& _return) = 0;
  virtual int32_t add(const int32_t num1, const int32_t num2) = 0;
};

class helloServiceIfFactory {
 public:
  typedef helloServiceIf Handler;

  virtual ~helloServiceIfFactory() {}

  virtual helloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(helloServiceIf* /* handler */) = 0;
};

class helloServiceIfSingletonFactory : virtual public helloServiceIfFactory {
 public:
  helloServiceIfSingletonFactory(const ::std::shared_ptr<helloServiceIf>& iface) : iface_(iface) {}
  virtual ~helloServiceIfSingletonFactory() {}

  virtual helloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(helloServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<helloServiceIf> iface_;
};

class helloServiceNull : virtual public helloServiceIf {
 public:
  virtual ~helloServiceNull() {}
  void hello_func(std::string& /* _return */) {
    return;
  }
  int32_t add(const int32_t /* num1 */, const int32_t /* num2 */) {
    int32_t _return = 0;
    return _return;
  }
};


class helloService_hello_func_args {
 public:

  helloService_hello_func_args(const helloService_hello_func_args&);
  helloService_hello_func_args& operator=(const helloService_hello_func_args&);
  helloService_hello_func_args() {
  }

  virtual ~helloService_hello_func_args() noexcept;

  bool operator == (const helloService_hello_func_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const helloService_hello_func_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const helloService_hello_func_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class helloService_hello_func_pargs {
 public:


  virtual ~helloService_hello_func_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _helloService_hello_func_result__isset {
  _helloService_hello_func_result__isset() : success(false) {}
  bool success :1;
} _helloService_hello_func_result__isset;

class helloService_hello_func_result {
 public:

  helloService_hello_func_result(const helloService_hello_func_result&);
  helloService_hello_func_result& operator=(const helloService_hello_func_result&);
  helloService_hello_func_result() : success() {
  }

  virtual ~helloService_hello_func_result() noexcept;
  std::string success;

  _helloService_hello_func_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const helloService_hello_func_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const helloService_hello_func_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const helloService_hello_func_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _helloService_hello_func_presult__isset {
  _helloService_hello_func_presult__isset() : success(false) {}
  bool success :1;
} _helloService_hello_func_presult__isset;

class helloService_hello_func_presult {
 public:


  virtual ~helloService_hello_func_presult() noexcept;
  std::string* success;

  _helloService_hello_func_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _helloService_add_args__isset {
  _helloService_add_args__isset() : num1(false), num2(false) {}
  bool num1 :1;
  bool num2 :1;
} _helloService_add_args__isset;

class helloService_add_args {
 public:

  helloService_add_args(const helloService_add_args&);
  helloService_add_args& operator=(const helloService_add_args&);
  helloService_add_args() : num1(0), num2(0) {
  }

  virtual ~helloService_add_args() noexcept;
  int32_t num1;
  int32_t num2;

  _helloService_add_args__isset __isset;

  void __set_num1(const int32_t val);

  void __set_num2(const int32_t val);

  bool operator == (const helloService_add_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const helloService_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const helloService_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class helloService_add_pargs {
 public:


  virtual ~helloService_add_pargs() noexcept;
  const int32_t* num1;
  const int32_t* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _helloService_add_result__isset {
  _helloService_add_result__isset() : success(false) {}
  bool success :1;
} _helloService_add_result__isset;

class helloService_add_result {
 public:

  helloService_add_result(const helloService_add_result&);
  helloService_add_result& operator=(const helloService_add_result&);
  helloService_add_result() : success(0) {
  }

  virtual ~helloService_add_result() noexcept;
  int32_t success;

  _helloService_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const helloService_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const helloService_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const helloService_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _helloService_add_presult__isset {
  _helloService_add_presult__isset() : success(false) {}
  bool success :1;
} _helloService_add_presult__isset;

class helloService_add_presult {
 public:


  virtual ~helloService_add_presult() noexcept;
  int32_t* success;

  _helloService_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class helloServiceClient : virtual public helloServiceIf {
 public:
  helloServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  helloServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello_func(std::string& _return);
  void send_hello_func();
  void recv_hello_func(std::string& _return);
  int32_t add(const int32_t num1, const int32_t num2);
  void send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class helloServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<helloServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (helloServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_hello_func(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  helloServiceProcessor(::std::shared_ptr<helloServiceIf> iface) :
    iface_(iface) {
    processMap_["hello_func"] = &helloServiceProcessor::process_hello_func;
    processMap_["add"] = &helloServiceProcessor::process_add;
  }

  virtual ~helloServiceProcessor() {}
};

class helloServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  helloServiceProcessorFactory(const ::std::shared_ptr< helloServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< helloServiceIfFactory > handlerFactory_;
};

class helloServiceMultiface : virtual public helloServiceIf {
 public:
  helloServiceMultiface(std::vector<std::shared_ptr<helloServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~helloServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<helloServiceIf> > ifaces_;
  helloServiceMultiface() {}
  void add(::std::shared_ptr<helloServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void hello_func(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello_func(_return);
    }
    ifaces_[i]->hello_func(_return);
    return;
  }

  int32_t add(const int32_t num1, const int32_t num2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(num1, num2);
    }
    return ifaces_[i]->add(num1, num2);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class helloServiceConcurrentClient : virtual public helloServiceIf {
 public:
  helloServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  helloServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void hello_func(std::string& _return);
  int32_t send_hello_func();
  void recv_hello_func(std::string& _return, const int32_t seqid);
  int32_t add(const int32_t num1, const int32_t num2);
  int32_t send_add(const int32_t num1, const int32_t num2);
  int32_t recv_add(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
